FROM espressif/idf:v5.4


RUN sed -i 's/d_type;/d_type; uint8_t d\[2\];/g' /opt/esp/tools/*/*/*/*/include/sys/dirent.h

ADD patches/*.patch /opt/esp/idf
RUN cd /opt/esp/idf && ls *.patch && git apply *.patch

ADD patches/lwip/*.patch /opt/esp/idf/components/lwip/lwip
RUN cd /opt/esp/idf/components/lwip/lwip && ls *.patch && git apply *.patch


ARG DOCKER_TAG

ARG TARGETARCH
ADD mgos_fw_meta.py $TARGETARCH/*lfs $TARGETARCH/*spiffs* /usr/local/bin/
ADD serve_core/ /opt/serve_core/
RUN ln -s /opt/serve_core/serve_core.py /usr/local/bin/serve_core.py

ARG DOCKER_TAG
ENV MGOS_TARGET_GDB /opt/Espressif/xtensa-esp32-elf/bin/xtensa-esp32-elf-gdb
ENV MGOS_TARGET_GDB_ESP32S3 /opt/Espressif/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gdb
ENV MGOS_TARGET_GDB_ESP32C3 /opt/Espressif/riscv32-esp-elf/bin/riscv32-esp-elf-gdb
ENV MGOS_SDK_REVISION $DOCKER_TAG
ENV MGOS_SDK_BUILD_IMAGE docker.io/mgos/esp32-build:$DOCKER_TAG
